<a href="https://colab.research.google.com/github/molemale/My-Practice/blob/master/Hamoye_Practice_work.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Practice**

Using numpy to code
arr= [6,7,8,9]
a= np.array(arr)
print(type(a),"with shape=",a.shape,",dtype =",a.dtype," and dimension",a.ndim).


In [ ]:
#trial
import numpy as np
arr=[6,7,8,9,10]
a=np.array(arr)
print(type(a),"with shape=",a.shape,",dtype =",a.dtype," and dimension",a.ndim)

<class 'numpy.ndarray'> with shape= (5,) ,dtype = int64  and dimension 1


In [ ]:
arr= [[1,2,3],[4,5,6]] #ndim no of dimension
b= np.array(arr)
print(type(b),"with shape=",b.shape,",dtype =",b.dtype," and dimension",b.ndim)

<class 'numpy.ndarray'> with shape= (2, 3) ,dtype = int64  and dimension 2


In [ ]:
print(np.zeros((2,3),dtype= int), #empty(), zeros(), ones(), full(), random.random(). you can also specify dtype(i.e int, float, stringetc.)
np.ones((2,3)) #2 here is no of box while 3 is the replication
,np.full((2,3),2.5)
,np.random.random((2,3)))

[[0 0 0]
 [0 0 0]] [[1. 1. 1.]
 [1. 1. 1.]] [[2.5 2.5 2.5]
 [2.5 2.5 2.5]] [[0.62536863 0.36631204 0.49759609]
 [0.86058836 0.56040071 0.92893772]]


In [ ]:
np.zeros((3)) #single array

array([0., 0., 0.])

In [ ]:
c = np.array([[9.0, 8.0, 7.0], [1.0, 2.0, 3.0]])
d = np.array([[4.0, 5.0, 6.0], [9.0, 8.0, 7.0]])
c+d # summing by matrix
#we could have other operations

c*d


array([[36., 40., 42.],
       [ 9., 16., 21.]])

In [ ]:
d/5

array([[0.8, 1. , 1.2],
       [1.8, 1.6, 1.4]])

In [ ]:
c**2

array([[81., 64., 49.],
       [ 1.,  4.,  9.]])

In [ ]:
d**2

array([[16., 25., 36.],
       [81., 64., 49.]])

In [ ]:
a[3] #all these are from the arrays we created in earlier cells

9

In [ ]:
a[4]

10

In [ ]:
b[0,0]

1

In [ ]:
d[1,  0:3] #note the diffrence here, d = np.array([[4.0, 5.0, 6.0], [9.0, 8.0, 7.0]])

array([9., 8., 7.])

In [ ]:
e = np.array([[10, 11, 12],[13, 14, 15],[16, 17, 18],[19, 20, 21]])
print(e)
e[0,1]
e[0,0:2]

[[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]]


array([10, 11])

In [ ]:
e[:3, :2] # slicing

array([[10, 11],
       [13, 14],
       [16, 17]])

In [ ]:
e[:2, :1]

array([[10],
       [13]])

In [ ]:
#There are other advanced methods of indexing which are shown below.
# integer indexing e = np.array([[10, 11, 12],[13, 14, 15],[16, 17, 18],[19, 20, 21]])
e[[2, 0, 3, 1],[2, 1, 0, 2]] #for example 18 is( located at 2,2 and 15 is located at 1,2) note that integers start at zero

array([18, 11, 19, 15])

In [ ]:
e[[0,2],[2,1]]# this should display 12 and 17

array([12, 17])

Observe another trend


In [ ]:
array([18, 11, 19, 15])

NameError: ignored

In [ ]:
e[e>15] # boolean indexing meeting a specified condition

Numpy can also do some mathematical function

In [ ]:
e.sum()   #when i tried e.sum got <function ndarray.sum> as a result cos i didnt use any bracket sign

In [ ]:
e.mean()

In [ ]:
#another way to write the code
np.std(e)

In [ ]:
e.std() # i tried this on my own and see what i got

In [ ]:
np.corrcoef(e,d) #pearson correlation between two arrays

#**Lesson 3 : Pandas**

**Creating Series and DataFrames in many ways**

In [ ]:
#Creating series and data frames in many ways
import pandas as pd
days = pd.Series(['Monday', 'Tuesday', 'Wednesday']) #trying something new
print(days)

In [ ]:
# creating series with a numpy array
days_list = np.array(['Monday', 'Tuesday', 'Wednesday'])
numpy_days = pd.Series(days_list)

In [ ]:
# using strings as index
days = pd.Series(['Monday', 'Tuesday', 'Wednesday'],
                 index=['a', 'b', 'c'])
print(days)

In [ ]:
# create series from a dictionary
days1 = pd.Series({'a':'Monday', 'b':'Tuesday', 'c':'Wednesday'})
print(days1)

In [ ]:
#Series can be accessed using the specified index as shown below
print (days[0], days[1: ], days['c'])   #i changed [0] to 'a'

In [ ]:
#A DataFrame can be described as a table (2 dimensions) made up of many series with the same index. It holds data in rows and columns just like a spreadsheet. Series, dictionaries, lists other dataframes and numpy arrays can be used to create new ones.
print(pd.DataFrame())  # prints an empty dataframe, this possible because we may not have created any


Data Frame
#How to create data frame#

In [ ]:
# create a dataframe from a dictionary
import pandas as pd
df_dict = {'Country': ['Ghana', 'Kenya', 'Nigeria', 'Togo'],
           'Capital': ['Accra', 'Nairobi', 'Abuja', 'Lome'],
           'Population': [10000, 8500, 35000, 12000],
           'Age': [60, 70, 80, 75]
}
df = pd.DataFrame(df_dict, index=[2, 4, 6, 8])
print(df)

In [ ]:
df['Capital']

In [ ]:
df.at[6, 'Country']

In [ ]:
df.iat[2, 0] #to pick nigera

In [ ]:
df.iat[1,1]

In [ ]:
df.iat[2,3]

In [ ]:
df.skew()

In [ ]:
df.describe()

In [ ]:
df.mode()

In [ ]:
df.median()

In [ ]:
#sorting for tables for missing values
import pandas as pd
import numpy as np

df_dict2 = {'Name': ['James', 'Yemen', 'Caro', np.nan],
           'Profession': ['Researcher', 'Artist', 'Doctor', 'Writer'],
           'Experience': [12, np.nan, 10, 8],
           'Height': [np.nan, 175, 180, 150]}

new_df = pd.DataFrame(df_dict2)
new_df

In [ ]:
# checking for cells with missing values as True
new_df.isnull()

In [ ]:
# remove rows with missing values
new_df.dropna()
#most rows have missing values we only have one complete row

In [ ]:
# wrangling data sets from different sources

#Read stored csv files
#csv_df = pd.read_csv(sample.csv) #to read convert a csv saved on your system to a dataframe
#csv_df.to_csv("name it",index=False) #to convert a dataframe in your notebook to a csv

#sometimes dependent on the xlrd library which can be installed by running pip install xlrd in the terminal
#excel_df = pd.read_excel('sample_file.xlsx')
#excel_df.to_excel('sample_file.xlsx')

#read table from a webpage and save as a dataframe
#html_df = pd.read_html('http://www.webpage.com/sampledata.html')
#html_df.to_html('sample_file.html')

In [ ]:
import pandas as pd
import numpy as np
public_utility_data_df= pd.read_csv("https://raw.githubusercontent.com/WalePhenomenon/climate_change/master/fuel_ferc1.csv")
public_utility_data_df.describe(include='all')

In [ ]:
public_utility_data_df.isnull().sum() 
# check for cells with missing values as True the .sum() shuws the results as this

In [ ]:
import pandas as pd
import numpy as np
public_utility_data_df= pd.read_csv("https://raw.githubusercontent.com/WalePhenomenon/climate_change/master/fuel_ferc1.csv")
public_utility_data_df[['fuel_unit']] = public_utility_data_df[['fuel_unit']].fillna(value='mcf') #fill the missing data with fillna
#check if missing values in fueldata have been filled
public_utility_data_df["fuel_unit"].isnull().sum()

In [ ]:
#use groupby to count the sum of each unique value in the fuel unit column
public_utility_data_df.groupby('fuel_unit')['fuel_unit'].count()

In [ ]:
public_utility_data_df.groupby('report_year')['report_year'].count()
#group by the fuel type code year shows the number of entries per year

In [ ]:
public_utility_data_df.groupby('fuel_type_code_pudl').last() #first()
#the column being analysed has 6 unique values so this code show the first time each of them appears in the data set

In [ ]:
import pandas as pd
import numpy as np
public_utility_data_df= pd.read_csv("https://raw.githubusercontent.com/WalePhenomenon/climate_change/master/fuel_ferc1.csv")
#merging of data frame
public_utility_data_df1 = public_utility_data_df.iloc[0:19000].reset_index(drop=True) # had issues here with naming
public_utility_data_df2 = public_utility_data_df.iloc[19000:].reset_index(drop=True)
#spliting dataframes

In [ ]:
#check that the length of both dataframes sum to the expected length: there is no error when i ran the code
assert len(public_utility_data_df) == (len(public_utility_data_df1) + len(public_utility_data_df2))

In [ ]:
#an inner merge will lose rows that do not match in both dataframes, this can also be done for outer merge

pd.merge(public_utility_data_df1, public_utility_data_df2, how="inner")

In [ ]:
pd.merge(public_utility_data_df1, public_utility_data_df2, how="outer") #this codes for an outer merge

In [ ]:
#removes rows from the right dataframe that do not have a match with the left
#and keeps all rows from the left
pd.merge(public_utility_data_df1, public_utility_data_df2, how="left")

In [ ]:
#Concatenation is performed with the concat() function by combining series or dataframes 
#while keeping the indices of the individual unit irrespective of duplicate indices. In the notebook, 
#we created a dummy dataframe data_to_concat which we concatenated to the fuel_data as below:
data_to_concat = pd.DataFrame(np.zeros(public_utility_data_df.shape))
pd.concat([public_utility_data_df, data_to_concat]).reset_index(drop=True)

In [ ]:
#Duplicates are a common occurrence in datasets which alter the results of data 
#analysis. Hence, in practice, removing duplicate values is very important. 
#The duplicated() function is used in Pandas to check for and handle duplicates.
public_utility_data_df.duplicated().any() #checking for duplicated rows

#Visualizing data#

In [ ]:
#import library to plot
import matplotlib.pyplot as plt
import seaborn as sns
import pandas.util.testing as tm # i got this line of instruction when i executed the code
# the line of code changed the calibration of my chart

plt.figure(figsize=(7,4))
plt.xticks(rotation=90)
public_utility_data_df = pd.DataFrame({'unit':['BBL', 'GAL', 'GRAMSU', 'KGU', 'MCF', 'MMBTU', 'MWDTH', 'MWHTH', 'TON'],
            'count':[7998, 84, 464, 110, 11354, 180, 95, 100, 8958]})
sns.barplot(data=public_utility_data_df, x='unit', y='count')
plt.xlabel('public_utility_data_df')

#Because of the extreme range of the values for the fuel unit, we can plot the barchart by taking the logarithm of the y-axis as follows:


g = sns.barplot(data=public_utility_data_df, x='unit', y='count')
g.set_yscale("log")
g.set_ylim(1, 12000)
plt.xlabel('Fuel Unit')

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns
import pandas.util.testing as tm
# Box plot
sns.boxplot(x="fuel_type_code_pudl", y="utility_id_ferc1",
            palette=["m", "g"], data=public_utility_data_df)


In [ ]:
# Select a sample of the dataset
sample_df = public_utility_data_df.sample(n=2000, random_state=4) # i had to change the no of sample from 20; for distribution

# KDE plot 
sns.kdeplot(sample_df['fuel_cost_per_unit_burned'], shade=True, color="b") #color code in py

In [ ]:
#SCATTER PLOT
sns.regplot(x=sample_df["utility_id_ferc1"], y=sample_df["fuel_cost_per_mmbtu"], fit_reg=False)
#my scatter diagram is differenet i change the number of my sample size

In [ ]:
sns.heatmap(sample_df.corr())
#i made a heatmap based on the level of correlation between the columns in the sample dataframe and one can see that fuel_cost_per_mmbtu
#is highly correlated with fuel_cost_per_unit deliver with a corellation above 0.8

#Done with the classes#

#Personal exploration#

#creating data frame list#

In [ ]:
import pandas as pd
import numpy as np
df_list = [['Ghana', 'Accra', 10000, 60], 
           ['Kenya', 'Nairobi', 8500, 70], 
           ['Nigeria',   'Abuja', 35000, 80], 
           ['Togo', 'Lome', 12000, 75]]
df1 = pd.DataFrame(df_list, columns=['Country', 'Capital','Population', 'Age'], 
                   index=[2, 4, 6, 8])
print(df1)
#two diiferent paths to get to the same answer(process looks similar like )

#using acessors#

##at, iat, iloc and loc are accessors used to retrieve data in dataframes. iloc selects values from the rows and columns by using integer index to locate positions while loc selects row or columns using labels. at and iat are used to retrieve single values such that at uses the column and row labels and iat uses indices.##

In [ ]:
import pandas as pd
df_list = [['Ghana', 'Accra', 10000, 60], 
           ['Kenya', 'Nairobi', 8500, 70], 
           ['Nigeria',   'Abuja', 35000, 80], 
           ['Togo', 'Lome', 12000, 75]]
df1 = pd.DataFrame(df_list, columns=['Country', 'Capital','Population', 'Age'], 
                   index=[2, 4, 6, 8])
print(df1)

In [ ]:
df1.iloc[3]  #select the row in the at index 3(i used df because its my last request)

In [ ]:
import pandas as pd
#df1['country']   # i replicated this on the data frame. ultered the code abit from the example given

In [ ]:

# minimum dimensions 
import numpy as np 
a = np.array([1, 2, 3,4,5], ndmin = 2) 
print (a)

# dtype parameter 
import numpy as np 
a = np.array([1, 2, 3], dtype = complex) 
print (a)




# convert list to ndarray 
import numpy as np 

x = [1,2,3,6,8,9] 
a = np.asarray(x) 
print (a)

# dtype as a set

x = [1,2,3,6,8,9] 
a = np.asarray(x, dtype=float)
print(a)

# ndarray from tuple. Tuple is a bit different, how? The bracket
import numpy as np
x=(1,2,3,5,7,8)
a=np.array(x)
print(x)

# ndarray from lists of tuples, here tuple as a list is in []
import numpy as np
x=[(1,2,3),(4,5,6,7)]
a=np.asarray(x)
print(x)

# we have be using np.asarry(x)


#numpy.frombuffer
#This function interprets a buffer as one-dimensional array. 
#Any object that exposes the buffer interface is used as parameter to return an ndarray.
#numpy.frombuffer(buffer, dtype = float, count = -1, offset = 0)

# i have issues using this 

# create list object using range function 
import numpy as np 
list = range(5) 
print (list)

#numpy.dtype(object, align, copy) this sytanx is used to configure data type

# using array-scalar type 
import numpy as np 
dt = np.dtype(np.int32) 
print (dt)


#int8, int16, int32, int64 can be replaced by equivalent string 'i1', 'i2','i4', etc. 
import numpy as np 

dt = np.dtype('i4')
print (dt) 


# using endian notation 
import numpy as np 
dt = np.dtype('>i4') 
print (dt)


# first create structured data type 
import numpy as np 
dt = np.dtype([('age',np.int8)]) 
print (dt)


# Applying it to ndarray object 
import numpy as np 

dt = np.dtype([('age',np.int8)]) 
a = np.array([(10,),(20,),(30,)], dtype= dt) 
print (a)

# file name can be used to access content of age column 
import numpy as np 

dt = np.dtype([('age',np.int8)]) 
a = np.array([(10,),(20,),(30,)], dtype = dt) 
print (a)


import numpy as np 
student = np.dtype([('name','S20'), ('age', 'i1'), ('marks', 'f4')]) 
print (student)


import numpy as np 
student = np.dtype([('name','S20'), ('age', 'i1'), ('marks', 'f4')]) 
h = np.array([('abc', 21, 50),('xyz', 18, 75)], dtype = student) 
print (h)